<a href="https://colab.research.google.com/github/xrosemaryc/Linear-Algebra_2nd-Sem/blob/main/Assignment5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Laboratory 3 : Matrix Operations

**Objectives**

At the end of this activity you will be able to:
1. Understand fundamental matrix operations.
2. Solve intermediate equations.
3. Solve engineering problems with matrix algebra.


##Discussion

The import keyword can make code from one code available in another. The import function is essential in organizing your codes and saving time by reusing what you imported. 
> Numerical Programming Libraries:
> *   **Numerical Python** is also known as ***numpy*** and uses ***np*** as a coding shortcut. It is a library of multidimensional arrays as well as a set of algorithms for manipulating which is helpful in conducting mathematical and logical array operations. [2]
> *   **Matplotlib** is also known as ***matplotlib.pyplot*** and uses ***plt*** as a coding shortcut. It is a library that helps in easier visualization and analysis of the data. This will help display the matrices.  [3]
> *   **SciPy** is also known as ***scipy.linalg*** and uses ***la*** as a coding shortcut. It is an open source library designed for science and engineering tasks.
This usually deals with linear algebra to help us perform tasks like matrix calculations. [4]


> Running the import code cell before everything below is important for your codes to function.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

## Transposition

Transposition is the act of transposing a matrix by switching its rows and columns to obtain its transpose. This is attained by exhanging an array A from array A [i] [j] into A [j] [i] [2]. In python, this can be done in a two ways, with the use of np.transpose(A) or A.T.

$$
A=\begin{bmatrix} -3 & 6 & 9 \\ 12 & -15 & 17 \\ 19 & 21 & -23 \end{bmatrix} \\
A^T = \begin{bmatrix} 3 & 12 & 19 \\ 6 & -15 & 21 \\ 9 & 17 & -23 \end{bmatrix} \\
$$

In [ ]:
MO = np.array([
    [-3, 6, 9],
    [12, -15, 17],
    [19, 21, -23]
])
MO

array([[ -3,   6,   9],
       [ 12, -15,  17],
       [ 19,  21, -23]])

In [ ]:
MO1 = np.transpose(MO)
MO1

array([[ -3,  12,  19],
       [  6, -15,  21],
       [  9,  17, -23]])

In [ ]:
MO2 = MO.T
MO2

array([[ -3,  12,  19],
       [  6, -15,  21],
       [  9,  17, -23]])

In [ ]:
np.array_equiv(MO1, MO2)

True

In [ ]:
MOB = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9],
    [-1,-2,-3],
    [-4,-5,-6],
    [-7,-8,-9],
])
MOB.shape

(6, 3)

In [ ]:
np.transpose(MOB).shape

(3, 6)

In [ ]:
MOB.T.shape

(3, 6)

Try to create your own matrix (you can try non-squares) to test transposition.

## Dot Product / Inner Product


Dot Product or Inner Product delivers the same result. It is an algebraic operation that operates matrices of two equal-sized vectors and returns a single scalar. The two matrices must be nonscalar, and their final dimensions must match. As an example,  $X$ and $Y$ are two matrices labled as:
$$
X =\begin{bmatrix} x_{(0,0)} & x_{(0,1)} \\ x_{(1,0)} & x_{(1,1)} \\ x_{(2,0)} & x_{(2,1)} \end{bmatrix}, 
Y =\begin{bmatrix} y_{(0,0)} & y_{(0,1)} & y_{(0,2)} \\ y_{(1,0)} & y_{(1,1)} & y_{(1,2)} \end{bmatrix} \\
$$

The dot product will then be computed as:

$$
X \cdot Y =\begin{bmatrix} x_{(0,0)}*y_{(0,0)} + x_{(0,1)}*y_{(1,0)} & x_{(0,0)}*y_{(0,1)} + x_{(0,1)}*y_{(1,1)} & x_{(0,0)}*y_{(0,2)} + x_{(0,1)}*y_{(1,2)}
\\ x_{(1,0)}*y_{(0,0)} + x_{(1,1)}*y_{(1,0)} & x_{(1,0)}*y_{(0,1)} + x_{(1,1)}*y_{(1,1)} & x_{(1,0)}*y_{(0,2)} + x_{(1,1)}*y_{(1,2)} \\ x_{(2,0)}*y_{(0,0)} + x_{(2,1)}*y_{(1,0)} & x_{(2,0)}*y_{(0,1)} + x_{(2,1)}*y_{(1,1)} & x_{(2,0)}*y_{(0,2)} + x_{(2,1)}*y_{(1,2)}  \end{bmatrix}
$$

The assigned values for $X$ and $Y$ are:
$$
X = \begin{bmatrix} 1&2 \\ 3&4 \\ 5&6 \end{bmatrix}, 
Y = \begin{bmatrix}-1&-2&-3 \\ -4&-5&-6 \end{bmatrix}
$$
We will acquire the sum of vector products by row-column pairings, which will return to a single number. Once substituted, the matrix will look like this:

$$
X \cdot Y =\begin{bmatrix} 1*-1 + 2*-4 & 1*-2 + 2*-5 & 1*-3+2*-6\\ 3*-1 + 4*-4 & 3*-2 + 4*-5 & 3*-3+4*-6 \\ 5*-1 + 6*-4 & 5*-2 + 6*-5 & 5*-3+6*-6 \end
{bmatrix} 
$$

and the dot product will be shown as:
$$
X \cdot Y =\begin{bmatrix}-9&-12&-15 \\ -19&-26&-33 \\ -29&-40&-51 \end{bmatrix}
$$

In [ ]:
X = np.array([
    [1,2],
    [3,4],
    [5,6]
])
Y = np.array([
    [-1,-2,-3],
    [-4,-5,-6]
])

In [ ]:
np.dot(X,Y)

array([[ -9, -12, -15],
       [-19, -26, -33],
       [-29, -40, -51]])

In [ ]:
X.dot(Y)

array([[ -9, -12, -15],
       [-19, -26, -33],
       [-29, -40, -51]])

In [ ]:
X @ Y


array([[ -9, -12, -15],
       [-19, -26, -33],
       [-29, -40, -51]])

In [ ]:
np.matmul(X,Y)

array([[ -9, -12, -15],
       [-19, -26, -33],
       [-29, -40, -51]])

## Rule 1: The inner dimensions of the two matrices in question must be the same.

During matrix multiplication, the main condition is that the inner dimensions of the two matrices must be the same in order to result in a matrix with the same dimensions as that of the outer dimensions of the multiplied matrices. An array A with dimensions of **m×n** and array B with dimensions **n×p** are multiplicable as they have the same inner dimensions. Multiplying these arrays would result in a matrix with dimensions **m×p**. 

$$
R =\begin{bmatrix} 1 & 2 & 4 \\ 5 & 7 & 9 \\ 3 & 6 & 9 \\ 4 & 8 & 12 \\ 6 & 12 & 18 \end{bmatrix}, 
O =\begin{bmatrix} -1 & -2 & 0 \\ -5 & -7 & 6 \\ -3 & -6 & 0 \end{bmatrix},
S =\begin{bmatrix} 0 & -2 & -4 & 2 & 4 \\ -5 & -7 & -9 & -7 & 0 \\ -3 & -6 & 0 & -9 & 3 \end{bmatrix} \\
$$

In [ ]:
R = np.array([
    [1, 2, 4],
    [5, 7, 9],
    [3, 6, 9],
    [4, 8, 12],
    [6, 12, 18]
])
O = np.array([
    [-1, -2, 0],
    [-5, -7, 6],
    [-3, -6, 0]
])
S = np.array([
    [0, -2, -4, 2, 4],
    [-5, -7, -9, -7, 0],
    [-3, -6, 0, -9 ,3]
])
print(R.shape)
print(O.shape)
print(S.shape)

(5, 3)
(3, 3)
(3, 5)


In [ ]:
R @ S

array([[ -22,  -40,  -22,  -48,   16],
       [ -62, -113,  -83, -120,   47],
       [ -57, -102,  -66, -117,   39],
       [ -76, -136,  -88, -156,   52],
       [-114, -204, -132, -234,   78]])

In [ ]:
O @ S

array([[ 10,  16,  22,  12,  -4],
       [ 17,  23,  83, -15,  -2],
       [ 30,  48,  66,  36, -12]])

In [ ]:
R @ O.T

array([[ -5,   5, -15],
       [-19, -20, -57],
       [-15,  -3, -45],
       [-20,  -4, -60],
       [-30,  -6, -90]])

In [ ]:
M = np.array([
    [1,2,3,4,-5,1,2,3,4,-6]
])
C = np.array([
    [-7,4,3,2,1,-2,4,3,2,1]
])
print(M.shape)
print(C.shape)

(1, 10)
(1, 10)


In [ ]:
C.T @ M

array([[ -7, -14, -21, -28,  35,  -7, -14, -21, -28,  42],
       [  4,   8,  12,  16, -20,   4,   8,  12,  16, -24],
       [  3,   6,   9,  12, -15,   3,   6,   9,  12, -18],
       [  2,   4,   6,   8, -10,   2,   4,   6,   8, -12],
       [  1,   2,   3,   4,  -5,   1,   2,   3,   4,  -6],
       [ -2,  -4,  -6,  -8,  10,  -2,  -4,  -6,  -8,  12],
       [  4,   8,  12,  16, -20,   4,   8,  12,  16, -24],
       [  3,   6,   9,  12, -15,   3,   6,   9,  12, -18],
       [  2,   4,   6,   8, -10,   2,   4,   6,   8, -12],
       [  1,   2,   3,   4,  -5,   1,   2,   3,   4,  -6]])

## Rule 2: Dot Product has special properties

Dot Product has five unique properties to discuss, namely:
1. Commutative Property - operates two matrices in a commutative way which result in unequal matrices and can be stated as: 
$A \cdot B \neq B \cdot A$

2. Associative Property - operates three or more matrices by interchanging the operation position using parentheses and still getting the same answer. This can be stated as:
$A \cdot (B \cdot C) = (A \cdot B) \cdot C$ or $A\cdot(B+C) = A\cdot B + A\cdot C$
3. Distributive Property - operates three or more matrices by distributing the operations for the matrices inside the parentheses and still getting the same answer. This can be stated as:
$(B+C)\cdot A = B⋅ A + C\cdot A$
4. Identity Property - a function used to return the identity of a given matrix. It can be stated as: 
 $A⋅ I = A$
5. Multiplicative Property of Zero - a function used to return the shape of a given matrix displaying zeroes in it. It can be stated as:
$A\cdot \emptyset = \emptyset$ 
 

In [ ]:
A = np.array([
    [1,3,5,7],
    [3,6,9,12],
    [6,12,18,24],
    [12,24,36,48]
])
B = np.array([
    [0,2,4,6],
    [2,4,6,8],
    [4,8,12,16],
    [8,16,24,32]
])
C = np.array([
    [2,0,2,2],
    [2,0,2,1],
    [2,0,2,0],
    [2,0,1,9]
])
D = np.zeros((4,4))

In [ ]:
one = A.dot(B)
one1 = B.dot(A)
print(f'A•B:\n{one}  \n\nB•A:\n{one1}\n')
print(f'Arrays are Commutative: {np.array_equal(one,one1)}')

A•B:
[[  82  166  250  334]
 [ 144  294  444  594]
 [ 288  588  888 1188]
 [ 576 1176 1776 2376]]  

B•A:
[[ 102  204  306  408]
 [ 146  294  442  590]
 [ 292  588  884 1180]
 [ 584 1176 1768 2360]]

Arrays are Commutative: False


In [ ]:
two = A.dot(B.dot(C))
two2 = (A.dot(B)).dot(C)
print(f'A•(B•C):\n{two}  \n\n(A•B)•C:\n{two2}\n')
print(f'Arrays are Associative: {np.array_equal(two,two2)}')

A•(B•C):
[[ 1664     0  1330  3336]
 [ 2952     0  2358  5928]
 [ 5904     0  4716 11856]
 [11808     0  9432 23712]]  

(A•B)•C:
[[ 1664     0  1330  3336]
 [ 2952     0  2358  5928]
 [ 5904     0  4716 11856]
 [11808     0  9432 23712]]

Arrays are Associative: True


In [ ]:
three = A.dot(B+C)
three3 = (A.dot(B))+(A.dot(C))
print(f'A•(B+C):\n{three}  \n\n(A•B)+(A•C):\n{three3}\n')
print(f'Arrays are Distributive: {np.array_equal(three,three3)}')

A•(B+C):
[[ 114  166  275  402]
 [ 204  294  492  714]
 [ 408  588  984 1428]
 [ 816 1176 1968 2856]]  

(A•B)+(A•C):
[[ 114  166  275  402]
 [ 204  294  492  714]
 [ 408  588  984 1428]
 [ 816 1176 1968 2856]]

Arrays are Distributive: True


In [ ]:
four = (B+C).dot(A)
four4 = (B.dot(A))+(C.dot(A))
print(f'(B+C)•A:\n{four}  \n\n(B•A)+(C•A):\n{four4}\n')
print(f'Arrays are Distributive: {np.array_equal(four,four4)}')

(B+C)•A:
[[ 140  282  424  566]
 [ 172  348  524  700]
 [ 306  618  930 1242]
 [ 700 1410 2120 2830]]  

(B•A)+(C•A):
[[ 140  282  424  566]
 [ 172  348  524  700]
 [ 306  618  930 1242]
 [ 700 1410 2120 2830]]

Arrays are Distributive: True


In [ ]:
five = A.dot(np.identity(4))
five5 = A
print(f'A•I:\n{five}  \n\nA:\n{five5}\n')
print(f'Arrays are Identical: {np.array_equal(five,five5)}')

A•I:
[[ 1.  3.  5.  7.]
 [ 3.  6.  9. 12.]
 [ 6. 12. 18. 24.]
 [12. 24. 36. 48.]]  

A:
[[ 1  3  5  7]
 [ 3  6  9 12]
 [ 6 12 18 24]
 [12 24 36 48]]

Arrays are Identical: True


In [ ]:
six = A.dot(D)
six6 = (D)
print(f'A•D:\n{six}  \n\nD:\n{six}\n')
print(f'Arrays are Multiplicative to Zero: {np.array_equal(six,six6)}')

A•D:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]  

D:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Arrays are Multiplicative to Zero: True


In [ ]:
A.dot(np.zeros(A.shape))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
zm = np.zeros(A.shape)
zm

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
adotz = A.dot(np.zeros(A.shape))
adotz


array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
np.array_equal(adotz,zm)

True

In [ ]:
null_mat = np.empty(A.shape, dtype=float)
null = np.array(null_mat,dtype=float)
print(null)
np.allclose(adotz,null)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


True

## Determinant

A determinant is a numerical output of an inputted square matrix array. These are useful in the analysis of solutions in linear algebra.  

Properties of determinants include [3]:
*   det $A^T$ = det A
*   det (AB) = det (A) det (B)
*   If a row or column of A is zero, det A = 0.
*   The determinant of an upper or lower triangular matrix is the product of its diagonal elements.
* $ A^-1 = adj(A)/det(A)  $

In [ ]:
A = np.array([
    [1,3],
    [5,7]
])
np.linalg.det(A)

-7.999999999999998

In [ ]:
B = np.array([
    [1,3,5],
    [7,9,11],
    [-2,-4,0]
])
np.linalg.det(B)

-72.0

In [ ]:
C = np.array([
    [1,3,2,4],
    [5,7,6,8],
    [0,0,11,9],
    [16,14,12,10]
])
np.linalg.det(C)

48.00000000000001

## Inverse

The inverse of a matrix is an algebraic operation used to find the solution of a system of linear equations. The matrix should not include 0 as its determinant. The inverse of a matrix is known as its reciprocal. The rechecking of an inverse matrix can be done using the dot product, in which the inverse of a matrix will be multiplied by the original matrix to solve for the identity matrix. 
The equation is stated as: $$AN ⋅ AN^{-1}=I$$


In [ ]:
D = np.array([
    [2,4],
    [6, 8]
])

np.array(D @ np.linalg.inv(D), dtype=int)

array([[1, 0],
       [0, 0]])

In [ ]:
E = np.array([
    [2,0,0,2,20],
    [51,1,9,7,1],
    [1,9,45,7,7],
    [2,0,0,21,1],
    [3,1,2,22,8],
])

F = np.linalg.inv(E)
np.array(E @ F,dtype=int)


array([[1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0],
       [0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0]])

In [ ]:
Birth = np.array([
    [1.0, 1.0, 0.5],
    [0.7, 0.7, 0.9],
    [0.3, 0.3, 1.0]
])
Day = np.array([
    [0.2, 0.2, 0.6]
])
Happy = Birth @ Day.T
Happy

array([[0.7 ],
       [0.82],
       [0.72]])

## Task 1

Task one (1) is an application of the concepts that have been taught during the lesson concerning the dot product/inner product matrix operation. This task contains the 5 special properties under the rule two (2) of the dot product operation, mainly:
* Commutative Property
* Associative Property
* Distributive Property
* Identity Property
* Multiplicative Property of Zero





In [ ]:
A = np.array([
    [1,3,5,7],
    [3,6,9,12],
    [6,12,18,24],
    [12,24,36,48]
])
B = np.array([
    [0,2,4,6],
    [2,4,6,8],
    [4,8,12,16],
    [8,16,24,32]
])
C = np.array([
    [2,0,2,2],
    [2,0,2,1],
    [2,0,2,0],
    [2,0,1,9]
])
D = np.zeros((4,4))

In [ ]:
one = A.dot(B)
one1 = B.dot(A)
print(f'A•B:\n{one}  \n\nB•A:\n{one1}\n')
print(f'Arrays are Commutative: {np.array_equal(one,one1)}')

A•B:
[[  82  166  250  334]
 [ 144  294  444  594]
 [ 288  588  888 1188]
 [ 576 1176 1776 2376]]  

B•A:
[[ 102  204  306  408]
 [ 146  294  442  590]
 [ 292  588  884 1180]
 [ 584 1176 1768 2360]]

Arrays are Commutative: False


In [ ]:
two = A.dot(B.dot(C))
two2 = (A.dot(B)).dot(C)
print(f'A•(B•C):\n{two}  \n\n(A•B)•C:\n{two2}\n')
print(f'Arrays are Associative: {np.array_equal(two,two2)}')

A•(B•C):
[[ 1664     0  1330  3336]
 [ 2952     0  2358  5928]
 [ 5904     0  4716 11856]
 [11808     0  9432 23712]]  

(A•B)•C:
[[ 1664     0  1330  3336]
 [ 2952     0  2358  5928]
 [ 5904     0  4716 11856]
 [11808     0  9432 23712]]

Arrays are Associative: True


In [ ]:
three = A.dot(B+C)
three3 = (A.dot(B))+(A.dot(C))
print(f'A•(B+C):\n{three}  \n\n(A•B)+(A•C):\n{three3}\n')
print(f'Arrays are Distributive: {np.array_equal(three,three3)}')

A•(B+C):
[[ 114  166  275  402]
 [ 204  294  492  714]
 [ 408  588  984 1428]
 [ 816 1176 1968 2856]]  

(A•B)+(A•C):
[[ 114  166  275  402]
 [ 204  294  492  714]
 [ 408  588  984 1428]
 [ 816 1176 1968 2856]]

Arrays are Distributive: True


In [ ]:
four = (B+C).dot(A)
four4 = (B.dot(A))+(C.dot(A))
print(f'(B+C)•A:\n{four}  \n\n(B•A)+(C•A):\n{four4}\n')
print(f'Arrays are Distributive: {np.array_equal(four,four4)}')

(B+C)•A:
[[ 140  282  424  566]
 [ 172  348  524  700]
 [ 306  618  930 1242]
 [ 700 1410 2120 2830]]  

(B•A)+(C•A):
[[ 140  282  424  566]
 [ 172  348  524  700]
 [ 306  618  930 1242]
 [ 700 1410 2120 2830]]

Arrays are Distributive: True


In [ ]:
five = A.dot(np.identity(4))
five5 = A
print(f'A•I:\n{five}  \n\nA:\n{five5}\n')
print(f'Arrays are Identical: {np.array_equal(five,five5)}')

A•I:
[[ 1.  3.  5.  7.]
 [ 3.  6.  9. 12.]
 [ 6. 12. 18. 24.]
 [12. 24. 36. 48.]]  

A:
[[ 1  3  5  7]
 [ 3  6  9 12]
 [ 6 12 18 24]
 [12 24 36 48]]

Arrays are Identical: True


In [ ]:
six = A.dot(D)
six6 = (D)
print(f'A•D:\n{six}  \n\nD:\n{six}\n')
print(f'Arrays are Multiplicative to Zero: {np.array_equal(six,six6)}')

A•D:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]  

D:
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

Arrays are Multiplicative to Zero: True
